# Invoking this pipeline requires additional permissions, so must be invoked
# in a way to pass those permissions on, e.g.:
#
#  build-phar:
#    permissions:
#      contents: read
#      id-token: write
#      attestations: write
#    uses: ./.github/workflows/build-phar.yml

name: "Build the PIE PHAR"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-phar:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-versions:
          - '8.1'
    permissions:
      # id-token:write is required for build provenance attestation.
      id-token: write
      # attestations:write is required for build provenance attestation.
      attestations: write
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: composer, box
          php-version: "${{ matrix.php-version }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Ensure some kind of previous tag exists, otherwise box fails
      - run: git describe --tags HEAD || git tag 0.0.0
      - uses: ramsey/composer-install@v3
      - name: Build PHAR
        run: box compile
      - name: Check the PHAR executes
        run: php pie.phar --version
      - name: Generate build provenance attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/pie.phar'
      - uses: actions/upload-artifact@v4
        with:
          name: pie-${{ github.sha }}.phar
          path: pie.phar
