name: "Publish the PHAR for Releases"

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build-phar:
    # See build-phar.yml for a list of the permissions and why they are needed
    permissions:
      contents: read
      id-token: write
      attestations: write
    uses: ./.github/workflows/build-phar.yml

  release-phar:
    runs-on: ubuntu-latest
    needs:
      - build-phar
    permissions:
      # contents:write is required to upload the binaries to the release.
      contents: write
    steps:
      - name: Fetch built PHAR from artifacts
        uses: actions/download-artifact@v4
        with:
          name: pie-${{ github.sha }}.phar
      - name: Verify the PHAR
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh attestation verify pie.phar --repo ${{ github.repository }}
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: pie.phar
